services:
  - type: web
    name: vesta-app
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.10
